moveit_simple_controller_manager:
  ros__parameters:
    controller_names:
      - left_joint_trajectory_controller
      - right_joint_trajectory_controller

    left_joint_trajectory_controller:
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      default: true
      joints:
        - left_fr3_joint1
        - left_fr3_joint2
        - left_fr3_joint3
        - left_fr3_joint4
        - left_fr3_joint5
        - left_fr3_joint6
        - left_fr3_joint7

    right_joint_trajectory_controller:
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      default: true
      joints:
        - right_fr3_joint1
        - right_fr3_joint2
        - right_fr3_joint3
        - right_fr3_joint4
        - right_fr3_joint5
        - right_fr3_joint6
        - right_fr3_joint7
