ontroller_manager:
  ros__parameters:
    update_rate: 100 # Hz

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster

left_franka_state_controller:
  type: franka_state_controller/FrankaStateController
  ros__parameters:
    arm_id: fr3 
    robot_ip: "dont_care"
    # All joint names must match the <joint> tags in the XACRO
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_f3_joint7

right_franka_state_controller:
  type: franka_state_controller/FrankaStateController
  ros__parameters:
    arm_id: fr3 
    robot_ip: "dont_care"
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7

left_joint_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_joint_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
